In [2]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import random
from datetime import datetime, timedelta

In [3]:
engine = create_engine("mysql+pymysql://root:SEEni2003%40@localhost:1611/ar_risk_system")

In [4]:
# Load All Tables:

customers_df = pd.read_sql("SELECT * FROM customers", engine)
invoices_df = pd.read_sql("SELECT * FROM invoices", engine)
payments_df = pd.read_sql("SELECT * FROM payments", engine)

In [5]:
# Print Customer Table:

customers_df.head()

  customer_id customer_type region  credit_limit risk_profile
0    CUST0001      Hospital  South     4232757.0          Low
1    CUST0002   Distributor   West     2883642.0       Medium
2    CUST0003      Hospital  South     1047247.0       Medium
3    CUST0004      Hospital  South     2797594.0       Medium
4    CUST0005   Distributor  North     1907053.0         High

In [6]:
# Print Invoice Table:

invoices_df.head()

  invoice_id customer_id invoice_date    due_date  invoice_amount
0   INV00001    CUST0306   2025-04-18  2025-06-17        173985.0
1   INV00002    CUST0092   2025-09-29  2025-11-28        739959.0
2   INV00003    CUST0188   2025-09-18  2025-11-17        280953.0
3   INV00004    CUST0075   2025-06-05  2025-08-04        268914.0
4   INV00005    CUST0268   2026-02-01  2026-04-02        397955.0

In [7]:
# Print Payments Tabe:

payments_df.head()

   payment_id invoice_id payment_date  payment_amount
0           1   INV00001   2025-07-21        173985.0
1           2   INV00002   2025-11-23        739959.0
2           3   INV00003   2025-11-19        280953.0
3           4   INV00004   2025-08-24        268914.0
4           5   INV00005   2026-04-02        397955.0

In [8]:
# Creation of AR Transactio  table:

ar_df = invoices_df.merge(
    payments_df,
    on="invoice_id",
    how="inner"
)

ar_df.head()

,invoice_id,customer_id,invoice_date,due_date,invoice_amount,payment_id,payment_date,payment_amount
0,INV00001,CUST0306,2025-04-18,2025-06-17,173985.0,1,2025-07-21,173985.0
1,INV00002,CUST0092,2025-09-29,2025-11-28,739959.0,2,2025-11-23,739959.0
2,INV00003,CUST0188,2025-09-18,2025-11-17,280953.0,3,2025-11-19,280953.0
3,INV00004,CUST0075,2025-06-05,2025-08-04,268914.0,4,2025-08-24,268914.0
4,INV00005,CUST0268,2026-02-01,2026-04-02,397955.0,5,2026-04-02,397955.0

In [9]:
ar_df.dtypes

invoice_id         object
customer_id        object
invoice_date       object
due_date           object
invoice_amount    float64
payment_id          int64
payment_date       object
payment_amount    float64
dtype: object

In [9]:
# Convert into dates:

ar_df["payment_date"] = pd.to_datetime(ar_df["payment_date"])
ar_df["due_date"] = pd.to_datetime(ar_df["due_date"])

In [10]:
# Calculation of Delay (Delay Days = Payment Date – Due Date)
ar_df["delay_days"] = (ar_df["payment_date"] - ar_df["due_date"]).dt.days

# Calculation of Delay Flag
ar_df["delay_flag"] = ar_df["delay_days"].apply(lambda x: 1 if x > 0 else 0)

In [11]:
# To Check Distribution:

ar_df["delay_flag"].value_counts()

delay_flag
1    7011
0    2989
Name: count, dtype: int64

In [12]:
# Aggregate per customer:

customer_features = ar_df.groupby("customer_id").agg(
    total_invoices=("invoice_id", "count"),
    total_amount=("invoice_amount", "sum"),
    avg_delay=("delay_days", "mean"),
    late_payment_rate=("delay_flag", "mean")
).reset_index()

In [12]:
# Attach Credit Limit to each invoice:

ar_df = ar_df.merge(
    customers_df[["customer_id","credit_limit"]],
    on="customer_id",
    how="left"
)

In [13]:
# Aggregate per customer.

customer_features = ar_df.groupby("customer_id").agg(
    total_invoices=("invoice_id", "count"),
    total_amount=("invoice_amount", "sum"),
    avg_delay=("delay_days", "mean"),
    max_delay=("delay_days", "max"),
    late_payment_rate=("delay_flag", "mean")
).reset_index()

In [14]:
# Add Credit Limit to Features:

customer_features = customer_features.merge(
    customers_df[["customer_id","credit_limit"]],
    on="customer_id",
    how="left"
)

In [15]:
# Create Credit Utilization (Credit Utilization = Total Amount / Credit Limit)

customer_features["credit_utilization"] = (
    customer_features["total_amount"] /
    customer_features["credit_limit"]
)

In [16]:
# Validate Missing values:

customer_features.isnull().sum()

customer_id           0
total_invoices        0
total_amount          0
avg_delay             0
max_delay             0
late_payment_rate     0
credit_limit          0
credit_utilization    0
dtype: int64

In [17]:
# Final Dataset Check:

customer_features.head()

,customer_id,total_invoices,total_amount,avg_delay,max_delay,late_payment_rate,credit_limit,credit_utilization
0,CUST0001,27,13268453.0,-1.555556,2,0.407407,4232757.0,3.134707
1,CUST0002,15,4200530.0,9.933333,13,1.000000,2883642.0,1.456675
2,CUST0003,23,6468998.0,11.478261,15,1.000000,1047247.0,6.177146
3,CUST0004,24,7270672.0,10.541667,15,1.000000,2797594.0,2.598902
4,CUST0005,24,4347214.0,34.416667,44,1.000000,1907053.0,2.279545

In [18]:
customer_features.to_sql(
    name="customer_features",
    con=engine,
    if_exists="replace",
    index=False
)

400